name: Build Lambda Function

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/lambda/python:3.11

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r modules/pingdb/src/requirements.txt -t modules/pingdb/src/

    - name: Create ZIP file
      run: |
        cd modules/pingdb/src
        zip -r ../../../lambda_function.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: lambda_function
        path: lambda_function.zip